In [5]:
import pandas as pd

In [6]:
pd.Series(5)

0    5
dtype: int64

In [7]:
pd.Series([1,2,3,4,5,6])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [8]:
a = {'A':["apple"], 'B':["Ball"], 'C':["cat"]}

In [9]:
pd.DataFrame(a)

       A     B    C
0  apple  Ball  cat

In [11]:
df = pd.read_csv('/content/Medicaldataset.csv')

In [12]:
type(df)

pandas.core.frame.DataFrame

In [13]:
df

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Result
0,64,1,66,160,83,160.0,1.80,0.012,negative
1,21,1,94,98,46,296.0,6.75,1.060,positive
2,55,1,64,160,77,270.0,1.99,0.003,negative
3,64,1,70,120,55,270.0,13.87,0.122,positive
4,55,1,64,112,65,300.0,1.08,0.003,negative
...,...,...,...,...,...,...,...,...,...
1314,44,1,94,122,67,204.0,1.63,0.006,negative
1315,66,1,84,125,55,149.0,1.33,0.172,positive
1316,45,1,85,168,104,96.0,1.24,4.250,positive
1317,54,1,58,117,68,443.0,5.80,0.359,positive
1318,51,1,94,157,79,134.0,50.89,1.770,positive

In [14]:
df.head()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Result
0,64,1,66,160,83,160.0,1.80,0.012,negative
1,21,1,94,98,46,296.0,6.75,1.060,positive
2,55,1,64,160,77,270.0,1.99,0.003,negative
3,64,1,70,120,55,270.0,13.87,0.122,positive
4,55,1,64,112,65,300.0,1.08,0.003,negative

In [15]:
df.head(10)

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Result
0,64,1,66,160,83,160.0,1.80,0.012,negative
1,21,1,94,98,46,296.0,6.75,1.060,positive
2,55,1,64,160,77,270.0,1.99,0.003,negative
3,64,1,70,120,55,270.0,13.87,0.122,positive
4,55,1,64,112,65,300.0,1.08,0.003,negative
5,58,0,61,112,58,87.0,1.83,0.004,negative
6,32,0,40,179,68,102.0,0.71,0.003,negative
7,63,1,60,214,82,87.0,300.00,2.370,positive
8,44,0,60,154,81,135.0,2.35,0.004,negative
9,67,1,61,160,95,100.0,2.84,0.011,negative

In [16]:
df.tail()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Result
1314,44,1,94,122,67,204.0,1.63,0.006,negative
1315,66,1,84,125,55,149.0,1.33,0.172,positive
1316,45,1,85,168,104,96.0,1.24,4.250,positive
1317,54,1,58,117,68,443.0,5.80,0.359,positive
1318,51,1,94,157,79,134.0,50.89,1.770,positive

In [17]:
df.tail(18)

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Result
1301,47,0,58,93,78,170.0,1.19,0.068,positive
1302,40,1,57,208,40,108.0,2.11,0.003,negative
1303,55,0,80,117,83,200.0,0.78,0.052,positive
1304,56,0,68,123,70,102.0,2.28,0.255,positive
1305,47,1,71,117,61,140.0,4.39,1.370,positive
1306,60,0,78,109,69,230.0,19.47,0.003,positive
1307,56,1,75,157,67,104.0,2.41,0.450,positive
1308,45,1,117,100,68,202.0,3.18,0.003,negative
1309,47,1,94,105,81,135.0,36.24,0.263,positive
1310,70,0,80,135,75,351.0,2.21,10.000,positive
1311,85,1,112,115,69,114.0,2.19,0.062,positive
1312,48,1,84,118,68,96.0,5.33,0.006,negative
1313,86,0,40,179,68,147.0,5.22,0.011,negative
1314,44,1,94,122,67,204.0,1.63,0.006,negative
1315,66,1,84,125,55,149.0,1.33,0.172,positive
1316,45,1,85,168,104,96.0,1.24,4.250,positive
1317,54,1,58,117,68,443.0,5.80,0.359,positive
1318,51,1,94,157,79,134.0,50.89,1.770,positive

In [18]:
df.shape

(1319, 9)

In [19]:
df.columns

Index(['Age', 'Gender', 'Heart rate', 'Systolic blood pressure',
       'Diastolic blood pressure', 'Blood sugar', 'CK-MB', 'Troponin',
       'Result'],
      dtype='object')

In [20]:
df['Heart rate']

0       66
1       94
2       64
3       70
4       64
        ..
1314    94
1315    84
1316    85
1317    58
1318    94
Name: Heart rate, Length: 1319, dtype: int64

In [21]:
type(df['Heart rate'])

pandas.core.series.Series

In [22]:
df[['Heart rate', 'Gender']]

      Heart rate  Gender
0             66       1
1             94       1
2             64       1
3             70       1
4             64       1
...          ...     ...
1314          94       1
1315          84       1
1316          85       1
1317          58       1
1318          94       1

[1319 rows x 2 columns]

In [23]:
type(df[['Heart rate', 'Gender']])

pandas.core.frame.DataFrame

operations on the given dataset

In [24]:
df['Systolic blood pressure'].sum()

np.int64(167738)

In [25]:
df['Heart rate'].value_counts()

Heart rate
60     95
61     57
70     48
64     47
80     46
       ..
107     1
49      1
46      1
36      1
45      1
Name: count, Length: 79, dtype: int64

In [26]:
df['Systolic blood pressure'].value_counts()

Systolic blood pressure
150    50
130    41
125    41
120    38
140    32
       ..
42      1
159     1
161     1
183     1
204     1
Name: count, Length: 116, dtype: int64

In [27]:
df['Age'].max()

103

In [28]:
df['Result'].min()

'negative'

In [29]:
df['Diastolic blood pressure'].mean()

np.float64(72.26914329037149)

In [30]:
df['Troponin'].std()

1.1545676649221834

In [31]:
df['Result'].count()

np.int64(1319)

In [33]:
avg = (df['Heart rate'].sum())/(df['Heart rate'].count())

In [35]:
avg

np.float64(78.3366186504928)